# Quick usage:
# 1. Install docker (+ gitbash on windows)
# 2. Open shell/gitbash
#    start: # docker-compose run -d
#    stop:  # docker-compose down
# To connect a terminal on windows (optionally prepend 'winpty' if cmd results in error:
#    docker exec -it <container name> bash
#
# Debug:
# - In a browser, Debug as PHP Web Page (set path mapping)
# - For CLI, listen to PHP Debug Connections, then open container bash and run app
#
# This file describes the services required to run this application.
# Single part definitions are located inside the appropriate docker service folder.
# Environment variables are defined in .env file which must be
# placed in the folder where docker-compose is called.
version: '3'

# Define the network
networks:
  web-network:

# Define the services
services:
  # corresponds to the "--name" parameter
  # However, service names are automatically prefixed
  # with the name of the parent folder to this file.

  db:
    image: mysql:${MYSQL_VERSION}
    command: --local-infile --default-authentication-plugin=mysql_native_password --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION" --innodb_strict_mode=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # defines the port mapping, corresponds to the "-p" flag, <external>:<internal>
    ports:
      - 3306:3306
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - web-network
    working_dir: /var/lib/mysql

  nginx:
    # if 'image' defined together with 'build', it's used as the build tag
    image: pronego/nginx:${FRAMEWORK}
    # Define the directory where the build should happen,
    # i.e. where the Dockerfile of the service is located
    # all paths are relatieve to the location of docker-compose.yml
    build:
      context: nginx-${FRAMEWORK}
    depends_on:
      - php
    # defines the port mapping, corresponds to the "-p" flag, <external>:<internal>
    ports:
      - "80:80"
    tty: true
    # mount the app_path directory of the host to /var/www in the container, corresponds to the "-v" option
    volumes:
      - ${APP_PATH}:/var/www/app
      - ${APP_PATH}/${DOCKER_PATH}/logs/nginx/:/var/log/nginx
    networks:
      - web-network

  php:
    image: pronego/php:${PHP_VERSION}
    build:
      context: php-${PHP_VERSION}
      args:
        TIMEZONE: ${TIMEZONE}
    tty: true
    volumes:
      - ${APP_PATH}:/var/www/app
    environment:
      # Set the name of the PHPStorm server configuration (Settings > Language & Frameworks > PHP > Servers)
      PHP_IDE_CONFIG: "serverName=localhost"
      XDEBUG_CONFIG: "remote_autostart=1"
    depends_on:
      - db
    networks:
      - web-network
    # Only required under Linux
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"

  # Call: http://[DOCKER-IP]:81
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      # Alternatively, use arbitrary host, asked for it on the login page
      #- PMA_ARBITRARY=1
    restart: always
    volumes:
      - ${APP_PATH}/${DOCKER_PATH}/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    ports:
      - 81:80
    networks:
      - web-network
    depends_on:
      - db

  # GitHub: https://github.com/fauria/docker-vsftpd
  # Docker: https://hub.docker.com/r/fauria/vsftpd
  ftp:
    image: fauria/vsftpd
    build:
      context: ./ftp
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
      - LOG_STDOUT=${LOG_STDOUT}
      - PASV_PROMISCUOUS=${PASV_PROMISCUOUS}
    restart: always
    ports:
      - 0.0.0.0:20:20
      - 0.0.0.0:21:21
      - 21100-21110:21100-21110
    volumes:
      - ${APP_PATH}/${DOCKER_PATH}/ftp/home:/home/vsftpd
      - ${APP_PATH}/${DOCKER_PATH}/logs/ftp:/var/log/vsftpd
    networks:
      - web-network
